### ISSUE TITLE
Undefined Attribute in SALTtrainingSN

### ISSUE THREAD

**Issue by Shin107** [djones1040/SALTShaker#270]
Hi,
While running the code following the instructions from SALTShaker documents, `trainsalt -c traingradient.conf`, I get an issue 
`Traceback (most recent call last):
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/TrainSALT.py", line 1202, in main
    x_modelpars,saltresids=self.initializesaltmodelobject(datadict)
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/TrainSALT.py", line 633, in initializesaltmodelobject
    return x_modelpars,saltresids.SALTResids(datadict,self.kcordict,modelconfiguration,self.options)
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/saltresids.py", line 383, in __init__
    self.datadict={snid: sn if isinstance(sn,SALTfitcacheSN) else SALTfitcacheSN(sn,self,self.kcordict,photpadding,specpadding)  for snid,sn in iterable}
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/saltresids.py", line 383, in <dictcomp>
    self.datadict={snid: sn if isinstance(sn,SALTfitcacheSN) else SALTfitcacheSN(sn,self,self.kcordict,photpadding,specpadding)  for snid,sn in iterable}
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/datamodels.py", line 576, in __init__
    setattr(self,attr, getattr(sndata,attr))
AttributeError: 'SALTtrainingSN' object has no attribute 'SIM_SALT2x0'
Traceback (most recent call last):
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/TrainSALT.py", line 1202, in main
    x_modelpars,saltresids=self.initializesaltmodelobject(datadict)
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/TrainSALT.py", line 633, in initializesaltmodelobject
    return x_modelpars,saltresids.SALTResids(datadict,self.kcordict,modelconfiguration,self.options)
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/saltresids.py", line 383, in __init__
    self.datadict={snid: sn if isinstance(sn,SALTfitcacheSN) else SALTfitcacheSN(sn,self,self.kcordict,photpadding,specpadding)  for snid,sn in iterable}
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/saltresids.py", line 383, in <dictcomp>
    self.datadict={snid: sn if isinstance(sn,SALTfitcacheSN) else SALTfitcacheSN(sn,self,self.kcordict,photpadding,specpadding)  for snid,sn in iterable}
  File "/home/animesh/miniconda3/envs/saltshaker/lib/python3.10/site-packages/saltshaker/training/datamodels.py", line 576, in __init__
    setattr(self,attr, getattr(sndata,attr))
AttributeError: 'SALTtrainingSN' object has no attribute 'SIM_SALT2x0'. Did you mean: 'SIM_SALT2x1'?`

To bypass this issue, I manually initialize SIM_SALT2x0, SIM_SALT2x1, and  SIM_SALT2c in the class SALTtrainingSN in readutils.py, by setting 
`self.SIM_SALT2x0=None #EDIT_animesh11dec
                self.SIM_SALT2x1=None
                self.SIM_SALT2c=None
` 
This works for now and the training runs but I am not sure how this would affect the training. 

On addition,  when I run with the option --steps_between_errorfit  (just to speed up the process to test SALT3) as stated in the docs, i get an error: 
```
usage: python TrainSALT.py -c <configfile> <options>

config file options can be overwridden at the command line
trainsalt: error: unrecognized arguments: --steps_between_errorfit
```

**Comment by djones1040** [comment]
sorry about that, should be fixed in the latest commit.  pip has also been updated, so hopefully no need to install from source.  You can use the `--fast` option to do a quicker test run of the software
